#!/bin/bash


echo "Running as $( whoami )..."

echo "Sending data..."

sudo find / > report.txt

echo "Data sent."

python3 find_string.py $1

echo "
Removing report file..."

rm report.txt

echo "Report file removed."

echo "Done."